name: KeyJawn
options:
  bundleIdPrefix: com.keyjawn
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "26.2"
  groupSortPosition: top
  createIntermediateGroups: true

packages:
  KeyJawnKit:
    path: KeyJawnKit
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    from: "1.2.5"
  Citadel:
    url: https://github.com/orlandos-nl/Citadel
    from: "0.11.1"
  SwiftNIO:
    url: https://github.com/apple/swift-nio
    from: "2.0.0"
  SwiftNIOSSH:
    url: https://github.com/Joannis/swift-nio-ssh
    from: "0.3.0"

targets:

  KeyJawn:
    type: application
    platform: iOS
    bundleId: com.keyjawn
    deploymentTarget: "17.0"
    sources:
      - path: KeyJawn
    dependencies:
      - package: KeyJawnKit
        product: KeyJawnKit
      - package: SwiftTerm
      - package: Citadel
      - package: SwiftNIO
        product: NIOCore
      - package: SwiftNIOSSH
        product: NIOSSH
      - target: KeyJawnKeyboard
        embed: true
    settings:
      base:
        SWIFT_VERSION: "6.0"
        PRODUCT_NAME: KeyJawn
        INFOPLIST_FILE: KeyJawn/Info.plist
        CODE_SIGN_ENTITLEMENTS: Configuration/KeyJawn.entitlements
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0.0"
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: KeyJawn/Info.plist
      properties:
        CFBundleName: KeyJawn
        CFBundleDisplayName: KeyJawn
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: LaunchScreenBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Voice input for terminal prompts"
        NSSpeechRecognitionUsageDescription: "Voice-to-text for typing prompts to CLI agents"
        NSPhotoLibraryUsageDescription: "Upload images via SFTP to insert paths into prompts"
        CFBundleURLTypes:
          - CFBundleURLName: com.keyjawn
            CFBundleURLSchemes:
              - keyjawn

  KeyJawnKeyboard:
    type: app-extension
    platform: iOS
    bundleId: com.keyjawn.KeyJawn.keyboard
    deploymentTarget: "17.0"
    sources:
      - path: KeyJawnKeyboard
    dependencies:
      - package: KeyJawnKit
        product: KeyJawnKit
    settings:
      base:
        SWIFT_VERSION: "6.0"
        PRODUCT_NAME: KeyJawnKeyboard
        PRODUCT_BUNDLE_IDENTIFIER: com.keyjawn.KeyJawn.keyboard
        INFOPLIST_FILE: KeyJawnKeyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: Configuration/KeyJawnKeyboard.entitlements
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
    info:
      path: KeyJawnKeyboard/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en-US
            RequestsOpenAccess: false
          NSExtensionPointIdentifier: com.apple.keyboard-input-mode
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).KeyboardViewController
